title: Wudi Alone
description: Wudi Alone Note
author: Wudi Alone
github: https://github.com/wudialone
about: Underground Researcher (Marxian Economics, Econometrics, etc. )
disqus_shortname: wudialone
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/wud_sq"
    - icon: fa-github
      link: "https://github.com/wud_sq"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml
    - text: category_name
      url: /category/category_name

url: "https://wud_sq.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
